# -*- Makefile -*-
#
# @file  Makefile.MidJaxonController
# @brief RTComponent makefile for "MidJaxonController component"
# @date  $Date$
#
# This file is generated by rtc-template with the following argments.
#
#  /usr/bin/rtc-template -bcxx --inport=u_in:TimedDoubleSeq  \
#  --outport=u_out:TimedDoubleSeq --module-name=MidJaxonController  
#
#
# $Id$
#
CXX      = `rtm-config --cxx`
CXXFLAGS = `rtm-config --cflags` -I.
LDFLAGS  = `rtm-config --libs`
SHFLAGS  = -shared

IDLC     = `rtm-config --idlc`
IDLFLAGS = `rtm-config --idlflags` -I`rtm-config --prefix`/include/rtm/idl
WRAPPER  = rtm-skelwrapper
WRAPPER_FLAGS = --include-dir="" --skel-suffix=Skel --stub-suffix=Stub

SKEL_OBJ =  
STUB_OBJ =  
IMPL_OBJ =  
OBJS     = MidJaxonController.o PDcontrollerMIDJAXON.o $(SKEL_OBJ) $(STUB_OBJ) $(IMPL_OBJ)

.SUFFIXES : .so

all: MidJaxonController.so PDcontrollerMIDJAXON.so


.cpp.o:
	rm -f $@
	$(CXX) $(CXXFLAGS) -c -o $@ $<

.o.so:
	rm -f $@
	$(CXX) $(SHFLAGS) -o $@ $(OBJS) $(LDFLAGS)

clean: clean_objs clean_skelstub
	rm -f *~

clean_objs:
	rm -f $(OBJS) MidJaxonController.so PDcontrollerMIDJAXON.so

clean_skelstub:
	rm -f *Skel.h *Skel.cpp
	rm -f *Stub.h *Stub.cpp


MidJaxonController.so: $(OBJS)
MidJaxonController.o: MidJaxonController.h  

PDcontrollerMIDJAXON.so: $(OBJS)
PDcontrollerMIDJAXON.o: PDcontrollerMIDJAXON.h  

install:
	mkdir -p /usr/lib/choreonoid-1.5/rtc
	cp PDcontrollerMIDJAXON.so MIDJAXON.PD.conf /usr/lib/choreonoid-1.5/rtc/

# end of Makefile

